# Generated by Django 3.2.6 on 2021-08-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvideo',
            old_name='coverPicture',
            new_name='overPicture',
        ),
    ]
