# Generated by Django 3.2.6 on 2021-08-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_coverpicture_addvideo_overpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvideo',
            old_name='overPicture',
            new_name='coverPicture',
        ),
    ]
