# Generated by Django 3.2.6 on 2021-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_overpicture_addvideo_coverpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvideo',
            old_name='user_language',
            new_name='videoLanguage',
        ),
        migrations.AddField(
            model_name='addvideo',
            name='addClass',
            field=models.CharField(choices=[('First', 1), ('Second', 2), ('Third', 3), ('Fourth', 4), ('Fifth', 5), ('Sixth', 6), ('Seventh', 7), ('Eighth', 8), ('Ninth', 9), ('Tenth', 10), ('Eleventh', 11), ('Twelfth', 1)], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
