# Generated by Django 3.2.6 on 2021-08-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210817_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvideo',
            name='video',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addvideo',
            name='coverPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
