# Generated by Django 3.2.4 on 2021-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210817_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvideo',
            name='subjectCategory',
            field=models.CharField(choices=[('Science', 'Science'), ('Social', 'Social'), ('Mathematics', 'Mathematics'), ('Coding', 'Coding'), ('Ethics & Soft Skills', 'Ethics & Soft Skills'), ('Environment', 'Environment'), ('Sustainability & Social Impact', 'Sustainability & Social Impact'), (' Language', [('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Sanskrit', 'Sanskrit'), ('Malayalam', 'Malayalam'), ('Bangali', 'Bangali'), ('Odia', 'Odia'), ('Urdu', 'Urdu'), ('Pali', 'Pali'), ('Marathi', 'Marathi'), ('Kannada', 'Kannada'), ('Parsian', 'Parsian'), ('Prakrit', 'Prakrit')])], max_length=31),
        ),
    ]
